name: NotifyIcon Library

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.5

      - name: Install dependencies
        run: dotnet restore NotifyIcon

      - name: Build
        run: dotnet build NotifyIcon --configuration Release --no-restore

      - name: Pack
        run: dotnet pack NotifyIcon\NotifyIcon.csproj -c Release --no-build -o out

      - name: Push NuGet package
        run: dotnet nuget push "out\*.nupkg" -k ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
